modLoader="javafml"
license="LGPLv3"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/Trinsdar/Traverse-Reforged/issues"

[[mods]]
modId="traverse_client"
version="${version}"
displayName="Traverse Reforged: client"
displayURL="https://github.com/Trinsdar/Traverse-Reforged"
credits="TerraformersMC for creating the fabric version"
authors="Trinsdar, Vaerian, NeusFear, TerraformersMC"
description='''A biome expansion mod that embraces the simplistic nature of Minecraft biomes'''
[[dependencies.traverse_client]]
modId="forge"
mandatory=true
versionRange="[43.2.0,)"
ordering="AFTER"
side="BOTH"
[[dependencies.traverse_client]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,)"
ordering="AFTER"
side="BOTH"
