modLoader="javafml"
license="LGPLv3"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Trinsdar/Traverse-Reforged/issues"

[[mods]]
modId="traverse_common"
version="${version}"
displayName="Traverse Reforged: Common"
displayURL="https://github.com/Trinsdar/Traverse-Reforged"
credits="TerraformersMC for creating the fabric version"
authors="Trinsdar, Vaerian, NeusFear, TerraformersMC"
description='''A biome expansion mod that embraces the simplistic nature of Minecraft biomes'''
[[dependencies.traverse_common]]
modId="forge"
mandatory=true
versionRange="[40.1.0,)"
ordering="AFTER"
side="BOTH"
[[dependencies.traverse_common]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,)"
ordering="AFTER"
side="BOTH"
[[dependencies.traverse_common]]
modId="terraform_utils"
mandatory=true
versionRange="[3.1.4,)"
ordering="AFTER"
side="BOTH"
[[dependencies.traverse_common]]
modId="terraform_wood_api_v1"
mandatory=true
versionRange="[3.1.3,)"
ordering="AFTER"
side="BOTH"
[[dependencies.traverse_common]]
modId="terraform_tree_api_v1"
mandatory=true
versionRange="[3.1.3,)"
ordering="AFTER"
side="BOTH"
